about page + duplicate phishing deleted
perttuvaarala/CatchMaster pull request #39
Opened 2023-10-08 20:17 UTC by roopeky

2023-10-08 20:20 UTC, adnanavni requested changes

2023-10-08 20:20 UTC, adnanavni commented on packages/app/src/components/About.tsx
> +            <p>Catchmaster was made in Web Development 2 course at Metropolia University by Group 2</p>
METROPOLIA UNIVERSITY OF APPLIED SCIENCES

2023-10-08 20:33 UTC, pennane commented on packages/app/src/components/About.tsx
> +    margin-right: 10px;
```suggestion
    margin-right: 0.625rem;
```

2023-10-08 20:33 UTC, pennane commented on packages/app/src/components/About.tsx
> +    margin-right: 10px;
px bad rem good, rem with 0.25 inverval best (i.e. 0.25rem, 0.5rem, 0.75rem)

2023-10-08 20:33 UTC, pennane commented on packages/app/src/components/About.tsx
> +                        <img width="20" height="20" src="https://img.icons8.com/ios/50/instagram-new--v1.png" alt="instagram-new--v1"/>
```suggestion
                        <StyledAuthorImage src="https://img.icons8.com/ios/50/instagram-new--v1.png" alt="instagram-new--v1"/>
```
maybe

2023-10-08 20:33 UTC, pennane commented on packages/app/src/components/About.tsx
> +const StyleBox = styled.div`
```suggestion
const StyledBox = styled.div`
```

2023-10-08 20:33 UTC, pennane commented on packages/app/src/components/About.tsx
> +const StyleSpan = styled.span`
```suggestion
const StyledSpan = styled.span`
```

2023-10-08 20:33 UTC, pennane commented on packages/app/src/components/About.tsx
> +            Join us at Catchmaster, just log in easily with your Google account and start sharing your fishing adventures today!
could maybe separate into multiple paragraphs so it looks automatically good in view

2023-10-08 20:33 UTC, pennane commented on packages/app/src/components/About.tsx
> +            <div>
```suggestion
            <ul>
```
afaik only `<li>` elements should be direct children of a `<ul>` element

2023-10-08 20:34 UTC, pennane commented on packages/app/src/components/About.tsx
> +                        <img width="20" height="20" src="https://img.icons8.com/ios/50/instagram-new--v1.png" alt="instagram-new--v1"/>
Actually there is already the <Image> component that you guys have implemented before, that could possibly be re-used here.

2023-10-09 09:39 UTC, adnanavni approved these changes

2023-10-09 09:39 UTC, merged